spring:
  application:
    name: handdoc
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

naver:
  clova:
    api-key-id: ${CLOVA_API_KEY_ID}
    api-key: ${CLOVA_API_KEY}

openai:
  api:
    key: ${OPEN_API_KEY}

management:
  endpoint:
    health:
      probes:
        enabled: true

  jwt:
    secret: ${JWT_SECRET}
    access:
      token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
