spring:
  application:
    name: handdoc
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      auto-index-creation: true # ??? ?? ??

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

server:
  port: 8080