spring:
  application:
    name: handdoc
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET}
    access:
      token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

naver:
  clova:
    api-key-id: ${CLOVA_API_KEY_ID}
    api-key: ${CLOVA_API_KEY}

openai:
  api:
    key: ${OPEN_API_KEY}

public-data:
  api:
    url: http://openapi.seoul.go.kr:8088/${SEOUL_API_KEY}/json/TbHospitalInfo

management:
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    display-request-duration: true